name: Mirror

on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  Deploy:
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'

      - name: Requirements
        run: pip install -r requirements.txt

      - name: Run
        run: python main.py
        env: 
          STREAMABLE_EMAIL: ${{ secrets.STREAMABLE_USERNAME }}
          STREAMABLE_PASSWORD: ${{ secrets.STREAMABLE_PASSWORD }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}

      - name: Upload 
        uses: Difegue/action-megacmd@master
        with:
          args: put ./clips nnys2021clips
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}