name: Mirror

on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Requirements
        run: pip install -r requirements.txt

      - name: Run
        run: python main.py
        env: 
          STREAMABLE_EMAIL: ${{ secrets.STREAMABLE_USERNAME }}
          STREAMABLE_PASSWORD: ${{ secrets.STREAMABLE_PASSWORD }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
